INSERT INTO audit_logs (id,transaction_id,decision,reason,action_taken,execution_result,stopping_rules_applied,created_at) VALUES
(61,4,'DIAGNOSIS_HUMAN_ESCALATION','Transaction flagged by risk filters due to suspicious velocity or security anomaly. Autonomous recovery halted for human review.','HUMAN_ESCALATION','RECOMMENDED','["Fraud flag detected by risk filters"]','2026-09-04 16:59:47.486537'),
(62,1,'EXECUTE_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','SUCCESS','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 0, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 5000.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:04:37.459232'),
(63,2,'EXECUTE_HUMAN_ESCALATION','Transaction has reached maximum safety retry threshold (3/3). Automated retries halted to prevent customer dispute.','HUMAN_ESCALATION','ESCALATED','{"retry_limit_passed": false, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 3, "triggered": true}, "high_value_rule": {"threshold": 20000.0, "current": 4200.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:04:37.840834'),
(64,3,'EXECUTE_HUMAN_ESCALATION','Transaction amount (₹25,000.00) exceeds autonomous recovery threshold (₹20,000.00). Requires merchant sign-off.','HUMAN_ESCALATION','ESCALATED','{"retry_limit_passed": true, "amount_threshold_passed": false, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 1, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 25000.0, "triggered": true}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:04:37.873749'),
(65,4,'EXECUTE_HUMAN_ESCALATION','Transaction flagged by risk filters due to suspicious velocity or security anomaly. Autonomous recovery halted for human review.','HUMAN_ESCALATION','ESCALATED','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": false, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 1, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 8500.0, "triggered": false}, "fraud_flag_rule": {"triggered": true}}','2026-09-04 17:04:37.912022'),
(66,5,'EXECUTE_PAYMENT_LINK','The registered card instrument has expired. A fresh payment link is required to collect updated credentials.','PAYMENT_LINK','SUCCESS','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 0, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 3500.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:04:37.942945'),
(67,6,'EXECUTE_PAYMENT_LINK','Declined due to insufficient funds with lower immediate balance likelihood. Dispatching alternative payment link for customer convenience.','PAYMENT_LINK','SUCCESS','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 1, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 1800.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:04:37.972261'),
(68,1,'EXECUTE_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','SUCCESS','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 0, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 5000.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:04:38.019317'),
(69,1,'EXECUTE_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','SUCCESS','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 0, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 5000.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:04:38.757288'),
(70,2,'EXECUTE_HUMAN_ESCALATION','Transaction has reached maximum safety retry threshold (3/3). Automated retries halted to prevent customer dispute.','HUMAN_ESCALATION','ESCALATED','{"retry_limit_passed": false, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 3, "triggered": true}, "high_value_rule": {"threshold": 20000.0, "current": 4200.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:04:38.770519'),
(71,1,'DIAGNOSIS_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','RECOMMENDED','[]','2026-09-04 17:05:56.025478'),
(72,1,'EXECUTE_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','SUCCESS','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 0, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 5000.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 17:05:56.044702'),
(73,2,'DIAGNOSIS_HUMAN_ESCALATION','Transaction has reached maximum safety retry threshold (3/3). Automated retries halted to prevent customer dispute.','HUMAN_ESCALATION','RECOMMENDED','["Max retries limit reached (retry_count 3 >= 3)"]','2026-09-04 17:05:56.106883'),
(74,3,'DIAGNOSIS_HUMAN_ESCALATION','Transaction amount (₹25,000.00) exceeds autonomous recovery threshold (₹20,000.00). Requires merchant sign-off.','HUMAN_ESCALATION','RECOMMENDED','["High-value transaction threshold exceeded (amount \u20b925,000.00 >= \u20b920,000.00)"]','2026-09-04 17:05:56.128077'),
(75,4,'DIAGNOSIS_HUMAN_ESCALATION','Transaction flagged by risk filters due to suspicious velocity or security anomaly. Autonomous recovery halted for human review.','HUMAN_ESCALATION','RECOMMENDED','["Fraud flag detected by risk filters"]','2026-09-04 17:05:56.153270')
ON CONFLICT DO NOTHING;