INSERT INTO audit_logs (id,transaction_id,decision,reason,action_taken,execution_result,stopping_rules_applied,created_at) VALUES
(31,150,'RECOVERED_AUTOMATICALLY','Baseline recovery executed for card_expired payment error.','RETRY','SUCCESS','{"max_retries_checked": true, "threshold_checked": true}','2026-09-02 04:19:07.147125'),
(32,159,'RECOVERED_AUTOMATICALLY','Baseline recovery executed for insufficient_funds payment error.','PAYMENT_LINK','SUCCESS','{"max_retries_checked": true, "threshold_checked": true}','2026-09-04 10:19:07.148898'),
(33,1,'EXECUTE_RETRY','Payment failed due to transient bank inter-switch latency. Previous customer record is strong (4 successful payments).','RETRY','SUCCESS','{"max_retries_rule": {"limit": 3, "current": 0, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 5000.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}, "bounded_mode": true}','2026-09-04 16:06:27.713189'),
(34,1,'DIAGNOSIS_RETRY','Payment failed due to transient bank inter-switch latency. Customer has strong past history (4 successful payments).','RETRY','RECOMMENDED','{"safety_checks": {"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true}, "stopping_rules_applied": []}','2026-09-04 16:46:11.082091'),
(35,2,'DIAGNOSIS_HUMAN_ESCALATION','Transaction has reached maximum safety retry threshold (3/3). Automated retries halted.','HUMAN_ESCALATION','RECOMMENDED','{"safety_checks": {"retry_limit_passed": false, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true}, "stopping_rules_applied": ["Max Retry Limit (3) Triggered -> Escalate to Human Review"]}','2026-09-04 16:46:11.605471'),
(36,3,'DIAGNOSIS_HUMAN_ESCALATION','Transaction amount (INR 25,000.00) exceeds autonomous threshold (INR 20,000.00). Requires merchant sign-off.','HUMAN_ESCALATION','RECOMMENDED','{"safety_checks": {"retry_limit_passed": true, "amount_threshold_passed": false, "fraud_check_passed": true, "test_mode": true}, "stopping_rules_applied": ["High-Value Threshold (INR 20,000.00) Triggered -> Escalate to Human Review"]}','2026-09-04 16:46:11.635119'),
(37,4,'DIAGNOSIS_HUMAN_ESCALATION','Transaction flagged by risk filters due to suspicious velocity or security anomaly.','HUMAN_ESCALATION','RECOMMENDED','{"safety_checks": {"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": false, "test_mode": true}, "stopping_rules_applied": ["Fraud Flag Rule Triggered -> Escalate to Human Review"]}','2026-09-04 16:46:11.684817'),
(38,1,'DIAGNOSIS_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','RECOMMENDED','[]','2026-09-04 16:53:57.329097'),
(39,1,'EXECUTE_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','SUCCESS','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 1, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 5000.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 16:53:57.402224'),
(40,2,'DIAGNOSIS_HUMAN_ESCALATION','Transaction has reached maximum safety retry threshold (3/3). Automated retries halted to prevent customer dispute.','HUMAN_ESCALATION','RECOMMENDED','["Max retries limit reached (retry_count 3 >= 3)"]','2026-09-04 16:53:57.482818'),
(41,3,'DIAGNOSIS_HUMAN_ESCALATION','Transaction amount (₹25,000.00) exceeds autonomous recovery threshold (₹20,000.00). Requires merchant sign-off.','HUMAN_ESCALATION','RECOMMENDED','["High-value transaction threshold exceeded (amount \u20b925,000.00 >= \u20b920,000.00)"]','2026-09-04 16:53:57.560092'),
(42,4,'DIAGNOSIS_HUMAN_ESCALATION','Transaction flagged by risk filters due to suspicious velocity or security anomaly. Autonomous recovery halted for human review.','HUMAN_ESCALATION','RECOMMENDED','["Fraud flag detected by risk filters"]','2026-09-04 16:53:57.589384'),
(43,1,'DIAGNOSIS_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','RECOMMENDED','[]','2026-09-04 16:57:33.477262'),
(44,1,'EXECUTE_RETRY','The failure appears temporary due to transient bank gateway latency, and the customer has a strong payment history (4 successful payments).','RETRY','SUCCESS','{"retry_limit_passed": true, "amount_threshold_passed": true, "fraud_check_passed": true, "test_mode": true, "max_retries_rule": {"limit": 3, "current": 2, "triggered": false}, "high_value_rule": {"threshold": 20000.0, "current": 5000.0, "triggered": false}, "fraud_flag_rule": {"triggered": false}}','2026-09-04 16:57:33.501517'),
(45,2,'DIAGNOSIS_HUMAN_ESCALATION','Transaction has reached maximum safety retry threshold (3/3). Automated retries halted to prevent customer dispute.','HUMAN_ESCALATION','RECOMMENDED','["Max retries limit reached (retry_count 3 >= 3)"]','2026-09-04 16:57:33.544258')
ON CONFLICT DO NOTHING;